"""targets_europe.py — 25 European countries, 1,600+ domains"""

TARGETS = {
    "Czech Republic": ["google.cz","seznam.cz","novinky.cz","idnes.cz","alza.cz","csas.cz","kb.cz","csob.cz","mall.cz","heureka.cz","rohlik.cz","o2.cz","vodafone.cz","bazos.cz","sreality.cz","jobs.cz","dr-max.cz","mvcr.cz","czso.cz","csfd.cz","blesk.cz","lidovky.cz","ihned.cz","aktualne.cz","ct24.cz","sport.cz","auto.cz","czc.cz","datart.cz","kasa.cz","pilulka.cz","dm.cz","lidl.cz","albert.cz","penny.cz","tesco.cz","kaufland.cz","bezrealitky.cz","profesia.cz","moneta.cz","raiffeisenbank.cz","fio.cz","upc.cz","t-mobile.cz","mfcr.cz","policie.cz","avast.com","eset.com","facebook.com","youtube.com","cd.cz","regiojet.cz","remax.cz","reality.cz"],
    "Poland": ["google.pl","allegro.pl","olx.pl","onet.pl","wp.pl","pkobp.pl","tvn24.pl","wyborcza.pl","empik.com","pracuj.pl","gov.pl","inpost.pl","mbank.pl","ceneo.pl","morele.net","filmweb.pl","zus.pl","lot.com","ryanair.com","gazeta.pl","bankier.pl","sport.pl","biedronka.pl","lidl.pl","otodom.pl","otomoto.pl","media-expert.pl","x-kom.pl","polsat.pl","tvp.pl","nbp.pl","pekao.com.pl","ing.pl","santander.pl","millennium.pl","play.pl","plus.pl","t-mobile.pl","orange.pl","apteka.pl","sejm.gov.pl","mf.gov.pl","facebook.com","youtube.com","instagram.com","linkedin.com","poczta-polska.pl","dpd.com.pl","booking.com","airbnb.pl"],
    "Hungary": ["google.hu","index.hu","origo.hu","otpbank.hu","telekom.hu","emag.hu","telex.hu","hvg.hu","rtlmost.hu","ingatlan.com","profession.hu","tesco.hu","nav.gov.hu","hazipatika.com","port.hu","jofogas.hu","portfolio.hu","444.hu","mediaklikk.hu","yettel.hu","digi.hu","vodafone.hu","mol.hu","aldi.hu","lidl.hu","spar.hu","penny.hu","auchan.hu","dm.hu","booking.com","wizzair.com","ryanair.com","k-h.hu","mkb.hu","raiffeisen.hu","cib.hu","mav.hu","bkk.hu","kormany.hu","parlament.hu","facebook.com","youtube.com","instagram.com","linkedin.com","mnb.hu","ksh.hu"],
    "Slovakia": ["google.sk","sme.sk","aktuality.sk","slsp.sk","tatrabanka.sk","alza.sk","topky.sk","joj.sk","profesia.sk","bazos.sk","slovensko.sk","refresher.sk","dennikn.sk","markiza.sk","o2.sk","orange.sk","digi.sk","telekom.sk","mall.sk","heureka.sk","nay.sk","dm.sk","tesco.sk","lidl.sk","billa.sk","kaufland.sk","csob.sk","vub.sk","365bank.sk","postovabanka.sk","ryanair.com","wizzair.com","vlada.gov.sk","nrsr.sk","prezident.sk","nbsk.sk","facebook.com","youtube.com","instagram.com","linkedin.com","zoznam.sk","azet.sk","cas.sk","pravda.sk"],
    "Romania": ["google.ro","digi24.ro","emag.ro","bcr.ro","olx.ro","prosport.ro","ing.ro","antena3.ro","imobiliare.ro","gov.ro","catena.ro","adevarul.ro","hotnews.ro","digi.ro","ejobs.ro","anaf.ro","brd.ro","raiffeisen.ro","unicredit.ro","kaufland.ro","lidl.ro","auchan.ro","carrefour.ro","mega-image.ro","penny.ro","elefant.ro","pcgarage.ro","altex.ro","cfrcalatori.ro","tarom.ro","wizzair.com","ryanair.com","bitdefender.com","farmacia.ro","remax.ro","autovit.ro","facebook.com","youtube.com","instagram.com","linkedin.com","presidency.ro","senat.ro","bnr.ro","tvr.ro"],
    "Serbia": ["google.rs","blic.rs","rts.rs","nbs.rs","kupujemprodajem.com","halo.rs","telegraf.rs","b92.net","vesti.rs","novosti.rs","komercijalna.rs","unicredit.rs","raiffeisen.rs","intesabank.rs","a1.rs","telenor.rs","mts.rs","sbb.rs","nekretnine.rs","halooglasi.com","polovniautomobili.com","bolnica.rs","apotekabeograd.rs","srbija.gov.rs","mfin.gov.rs","apr.gov.rs","facebook.com","youtube.com","instagram.com","linkedin.com","rts.rs","pink.rs","ekapija.com"],
    "Croatia": ["google.hr","index.hr","njuskalo.hr","jutarnji.hr","hrt.hr","hnb.hr","24sata.hr","vecernji.hr","telegram.hr","dnevnik.hr","rtl.hr","pbz.hr","zaba.hr","erste.hr","otp.hr","addiko.hr","hpb.hr","a1.hr","telekom.hr","vipnet.hr","njuskalo.hr","crozilla.com","auto.hr","hzjz.hr","ljekarne.hr","benu.hr","vlada.gov.hr","sabor.hr","dzs.hr","booking.com","airbnb.hr","jadrolinija.hr","facebook.com","youtube.com","instagram.com","linkedin.com"],
    "Slovenia": ["google.si","rtvslo.si","24ur.com","sta.si","nkbm.si","delo.si","dnevnik.si","finance.si","zurnal24.si","siol.net","ska.si","abanka.si","unicredit.si","sparkasse.si","a1.si","telekom.si","telemach.si","mimovrste.com","mercator.si","spar.si","lidl.si","nepremicnine.net","remax.si","avto.net","nijz.si","zzzs.si","krka.si","lek.si","gov.si","dz-rs.si","ajpes.si","facebook.com","youtube.com","instagram.com","linkedin.com"],
    "Bosnia and Herzegovina": ["google.ba","klix.ba","bljesak.info","avaz.ba","nezavisne.com","oslobodjenje.ba","radiosarajevo.ba","bhrt.ba","rtrs.tv","unicredit.ba","raiffeisen.ba","sparkasse.ba","nlb.ba","bhtelecom.ba","telekom.ba","mtel.ba","logosoft.net","olx.ba","nekretnineba.ba","autopijaca.ba","kbcsarajevo.ba","fbihvlada.gov.ba","cbbh.ba","facebook.com","youtube.com","instagram.com","linkedin.com"],
    "North Macedonia": ["google.mk","vest.mk","slobodenpecat.mk","mkd.mk","telema.com.mk","kanal5.mk","plusinfo.mk","meta.mk","sdk.mk","time.mk","stopanska.com.mk","komercijalna.mk","nlb.mk","sparkasse.mk","telekom.mk","a1.mk","one.mk","blizoo.mk","pazar3.mk","oglasi.mk","avtopazar.mk","gov.mk","sobranie.mk","nbrm.mk","facebook.com","youtube.com","instagram.com","linkedin.com","mrt.com.mk","nova.mk","channel5.com.mk"],
    "Estonia": ["google.ee","delfi.ee","err.ee","postimees.ee","eesti.ee","seb.ee","swedbank.ee","lhv.ee","luminor.ee","coop.ee","rimi.ee","maxima.ee","barbora.ee","telia.ee","elisa.ee","tele2.ee","apollo.ee","kaup24.ee","euronics.ee","kv.ee","city24.ee","osta.ee","auto24.ee","apotheka.ee","benu.ee","synlab.ee","riik.ee","riigikogu.ee","mkm.ee","facebook.com","youtube.com","instagram.com","linkedin.com","hot.ee","forte.ee","geenius.ee"],
    "Latvia": ["google.lv","delfi.lv","tvnet.lv","la.lv","db.lv","swedbank.lv","seb.lv","luminor.lv","citadele.lv","rietumu.lv","rimi.lv","maxima.lv","barbora.lv","lmt.lv","tele2.lv","bite.lv","tet.lv","ss.lv","city24.lv","auto.lv","sixt.lv","dr.lv","veselibascenter.lv","benu.lv","apoteka.lv","latvija.lv","saeima.lv","lursoft.lv","vid.gov.lv","facebook.com","youtube.com","instagram.com","linkedin.com","lsm.lv","inbox.lv","apollo.lv"],
    "Lithuania": ["google.lt","delfi.lt","lrt.lt","15min.lt","lb.lt","vz.lt","swedbank.lt","seb.lt","luminor.lt","siauliu.lt","rimi.lt","maxima.lt","iki.lt","barbora.lt","senukai.lt","tele2.lt","bite.lt","telia.lt","cgates.lt","skelbiu.lt","aruodas.lt","nt.lt","autoplius.lt","pigu.lt","varle.lt","synlab.lt","benu.lt","eurovaistine.lt","lrv.lt","seimas.lt","sodra.lt","vmi.lt","facebook.com","youtube.com","instagram.com","linkedin.com","alfa.lt"],
    "Germany": ["google.de","amazon.de","ebay.de","spiegel.de","bild.de","sueddeutsche.de","tagesschau.de","focus.de","stern.de","welt.de","faz.net","handelsblatt.com","dkb.de","ing.de","commerzbank.de","deutschebank.de","sparkasse.de","postbank.de","telekom.de","vodafone.de","o2online.de","1und1.de","otto.de","zalando.de","mediamarkt.de","saturn.de","lidl.de","aldi.de","rewe.de","edeka.de","kaufland.de","immobilienscout24.de","immowelt.de","autoscout24.de","mobile.de","adac.de","shop-apotheke.com","bundesregierung.de","bundestag.de","bundesbank.de","destatis.de","facebook.com","youtube.com","instagram.com","linkedin.com"],
    "Austria": ["google.at","orf.at","kurier.at","derstandard.at","diepresse.com","krone.at","kleinezeitung.at","heute.at","erste.at","bawagpsk.at","raiffeisen.at","unicredit.at","volksbank.at","a1.net","magenta.at","drei.at","hot.at","willhaben.at","zalando.at","spar.at","billa.at","hofer.at","lidl.at","merkur.at","immobilienscout24.at","remax.at","autoscout24.at","mobile.de","gesundheit.at","DocFinder.at","apotheker.at","bundeskanzleramt.gv.at","parlament.gv.at","oenb.at","statistik.at","facebook.com","youtube.com","instagram.com","linkedin.com"],
    "Switzerland": ["google.ch","srf.ch","blick.ch","nzz.ch","watson.ch","20min.ch","tagesanzeiger.ch","rts.ch","swissinfo.ch","ubs.com","postfinance.ch","raiffeisen.ch","swisscom.ch","sunrise.ch","salt.ch","upc.ch","ricardo.ch","tutti.ch","digitec.ch","galaxus.ch","migros.ch","coop.ch","lidl.ch","aldi.ch","denner.ch","homegate.ch","comparis.ch","immoscout24.ch","autoscout24.ch","carforyou.ch","toppharm.ch","medgate.ch","admin.ch","snb.ch","bfs.admin.ch","facebook.com","youtube.com","instagram.com","linkedin.com"],
    "Sweden": ["google.se","dn.se","svt.se","aftonbladet.se","expressen.se","sydsvenskan.se","di.se","metro.se","omni.se","swedbank.se","seb.se","handelsbanken.se","nordea.se","tele2.se","telia.se","telenor.se","tre.se","blocket.se","tradera.se","prisjakt.se","pricerunner.se","ica.se","coop.se","lidl.se","willys.se","mathem.se","hemnet.se","booli.se","bytbil.com","wayke.se","mobile.de","vardguiden.se","kry.se","apoteket.se","government.se","riksdagen.se","riksbank.se","scb.se","skatteverket.se","facebook.com","youtube.com","instagram.com","linkedin.com"],
    "Norway": ["google.no","vg.no","nrk.no","dagbladet.no","aftenposten.no","tv2.no","dn.no","e24.no","nettavisen.no","dnb.no","nordea.no","sparebank1.no","sbanken.no","telenor.no","telia.no","ice.no","onecall.no","finn.no","komplett.no","power.no","elkjop.no","kiwi.no","rema1000.no","coop.no","meny.no","obos.no","naf.no","bruktbil.no","helsenorge.no","apotek1.no","vitusapotek.no","regjeringen.no","stortinget.no","norgesbank.no","ssb.no","facebook.com","youtube.com","instagram.com","linkedin.com"],
    "Denmark": ["google.dk","dr.dk","tv2.dk","bt.dk","politiken.dk","berlingske.dk","ekstrabladet.dk","borsen.dk","computerworld.dk","nordea.dk","jyskebank.dk","sydbank.dk","lunar.app","tdc.dk","telenor.dk","telia.dk","3.dk","pricerunner.dk","edc.dk","bilka.dk","netto.dk","rema1000.dk","meny.dk","boligsiden.dk","nybolig.dk","danbolig.dk","bilbasen.dk","biltorvet.dk","mobile.de","sundhed.dk","apotek.dk","matas.dk","stm.dk","ft.dk","nationalbanken.dk","dst.dk","politi.dk","facebook.com","youtube.com","instagram.com","linkedin.com"],
    "Finland": ["google.fi","yle.fi","hs.fi","iltalehti.fi","is.fi","mtv.fi","kauppalehti.fi","op.fi","nordea.fi","aktia.fi","handelsbanken.fi","elisa.fi","telia.fi","dna.fi","verkkokauppa.com","gigantti.fi","motonet.fi","kesko.fi","s-kanava.fi","lidl.fi","prisma.fi","alepa.fi","etuovi.com","oikotie.fi","tori.fi","nettiauto.com","traficom.fi","terveystalo.com","mehilainen.fi","yliopiston-apteekki.fi","valtioneuvosto.fi","eduskunta.fi","stat.fi","poliisi.fi","facebook.com","youtube.com","instagram.com","linkedin.com"],
    "France": ["google.fr","lemonde.fr","lefigaro.fr","bfmtv.com","francetvinfo.fr","20minutes.fr","liberation.fr","leparisien.fr","ouest-france.fr","bnpparibas.fr","societegenerale.fr","credit-agricole.fr","lcl.fr","caisse-epargne.fr","orange.fr","sfr.fr","bouyguestelecom.fr","free.fr","amazon.fr","cdiscount.com","fnac.com","darty.com","boulanger.com","ldlc.com","carrefour.fr","leclerc.fr","auchan.fr","lidl.fr","leboncoin.fr","seloger.com","lacentrale.fr","autoscout24.fr","doctolib.fr","ameli.fr","elysee.fr","gouvernement.fr","assemblee-nationale.fr","banque-france.fr","sncf.com","ratp.fr","airfrance.com","facebook.com","youtube.com","instagram.com","linkedin.com","pole-emploi.fr","impots.gouv.fr"],
    "United Kingdom": ["google.co.uk","bbc.co.uk","theguardian.com","dailymail.co.uk","telegraph.co.uk","thetimes.co.uk","independent.co.uk","thesun.co.uk","sky.com","itv.com","hsbc.co.uk","barclays.co.uk","lloydsbank.com","natwest.com","santander.co.uk","monzo.com","vodafone.co.uk","ee.co.uk","o2.co.uk","three.co.uk","bt.com","amazon.co.uk","ebay.co.uk","argos.co.uk","currys.co.uk","john-lewis.com","next.co.uk","tesco.com","asda.com","sainsburys.co.uk","morrisons.com","waitrose.com","rightmove.co.uk","zoopla.co.uk","autotrader.co.uk","gumtree.com","nhs.uk","boots.com","superdrug.com","gov.uk","parliament.uk","bankofengland.co.uk","hmrc.gov.uk","easyjet.com","ryanair.com","britishairways.com","facebook.com","youtube.com","instagram.com","linkedin.com"],
    "Spain": ["google.es","el-pais.com","marca.com","as.com","elconfidencial.com","abc.es","elmundo.es","lavanguardia.com","20minutos.es","rtve.es","antena3.com","santander.com","bbva.com","caixabank.es","sabadell.com","movistar.es","vodafone.es","orange.es","yoigo.com","masmovil.es","amazon.es","pccomponentes.com","mediamarkt.es","elcorteingles.es","zara.com","mango.com","mercadona.es","carrefour.es","lidl.es","alcampo.es","dia.es","idealista.com","fotocasa.es","coches.net","autoscout24.es","wallapop.com","sanitas.es","mapfre.es","lamoncloa.gob.es","congreso.es","bde.es","ine.es","booking.com","iberia.com","vueling.com","ryanair.com","facebook.com","youtube.com","instagram.com","linkedin.com"],
    "Portugal": ["google.pt","publico.pt","jn.pt","dn.pt","cmjornal.pt","sapo.pt","rtp.pt","sic.pt","tvi.pt","observador.pt","cgd.pt","millenniumbcp.pt","novobanco.pt","santander.pt","nos.pt","meo.pt","vodafone.pt","fnac.pt","worten.pt","pingo-doce.pt","continente.pt","lidl.pt","aldi.pt","intermarche.pt","imovirtual.com","idealista.pt","remax.pt","standvirtual.com","autosapo.pt","olx.pt","sns24.gov.pt","farmacias.saude.pt","portugal.gov.pt","parlamento.pt","bportugal.pt","ine.pt","booking.com","tap.pt","ryanair.com","cp.pt","metro.pt","facebook.com","youtube.com","instagram.com","linkedin.com"],
    "Italy": ["google.it","corriere.it","repubblica.it","gazzetta.it","lastampa.it","ilsole24ore.com","ansa.it","sky.it","mediaset.it","rai.it","la7.it","intesasanpaolo.com","unicredit.it","mps.it","bper.it","tim.it","vodafone.it","wind3.it","fastweb.it","iliad.it","amazon.it","ebay.it","mediaworld.it","unieuro.it","euronics.it","esselunga.it","conad.it","coop.it","carrefour.it","lidl.it","eurospin.it","immobiliare.it","idealista.it","tecnocasa.it","autoscout24.it","subito.it","doctolib.it","farmacia.it","governo.it","camera.it","senato.it","bancaditalia.it","istat.it","trenitalia.com","ryanair.com","easyjet.com","facebook.com","youtube.com","instagram.com","linkedin.com","poste.it","inps.it"],
}

COUNTRY_META = {
    "Czech Republic":         {"code":"cz","flag":"🇨🇿","region":"CEE"},
    "Poland":                 {"code":"pl","flag":"🇵🇱","region":"CEE"},
    "Hungary":                {"code":"hu","flag":"🇭🇺","region":"CEE"},
    "Slovakia":               {"code":"sk","flag":"🇸🇰","region":"CEE"},
    "Romania":                {"code":"ro","flag":"🇷🇴","region":"CEE"},
    "Serbia":                 {"code":"rs","flag":"🇷🇸","region":"Balkans"},
    "Croatia":                {"code":"hr","flag":"🇭🇷","region":"Balkans"},
    "Slovenia":               {"code":"si","flag":"🇸🇮","region":"Balkans"},
    "Bosnia and Herzegovina": {"code":"ba","flag":"🇧🇦","region":"Balkans"},
    "North Macedonia":        {"code":"mk","flag":"🇲🇰","region":"Balkans"},
    "Estonia":                {"code":"ee","flag":"🇪🇪","region":"Baltics"},
    "Latvia":                 {"code":"lv","flag":"🇱🇻","region":"Baltics"},
    "Lithuania":              {"code":"lt","flag":"🇱🇹","region":"Baltics"},
    "Germany":                {"code":"de","flag":"🇩🇪","region":"DACH"},
    "Austria":                {"code":"at","flag":"🇦🇹","region":"DACH"},
    "Switzerland":            {"code":"ch","flag":"🇨🇭","region":"DACH"},
    "Sweden":                 {"code":"se","flag":"🇸🇪","region":"Nordics"},
    "Norway":                 {"code":"no","flag":"🇳🇴","region":"Nordics"},
    "Denmark":                {"code":"dk","flag":"🇩🇰","region":"Nordics"},
    "Finland":                {"code":"fi","flag":"🇫🇮","region":"Nordics"},
    "France":                 {"code":"fr","flag":"🇫🇷","region":"Western"},
    "United Kingdom":         {"code":"gb","flag":"🇬🇧","region":"Western"},
    "Spain":                  {"code":"es","flag":"🇪🇸","region":"Western"},
    "Portugal":               {"code":"pt","flag":"🇵🇹","region":"Western"},
    "Italy":                  {"code":"it","flag":"🇮🇹","region":"Western"},
}

REGIONS = {
    "CEE":     ["Czech Republic","Poland","Hungary","Slovakia","Romania"],
    "Balkans": ["Serbia","Croatia","Slovenia","Bosnia and Herzegovina","North Macedonia"],
    "Baltics": ["Estonia","Latvia","Lithuania"],
    "DACH":    ["Germany","Austria","Switzerland"],
    "Nordics": ["Sweden","Norway","Denmark","Finland"],
    "Western": ["France","United Kingdom","Spain","Portugal","Italy"],
}

if __name__ == "__main__":
    total = sum(len(v) for v in TARGETS.values())
    print(f"Domains : {total}")
    print(f"Countries: {len(TARGETS)}")
    for region, countries in REGIONS.items():
        count = sum(len(TARGETS.get(c,[])) for c in countries)
        print(f"  {region:10s}: {len(countries)} countries, {count} domains")
